version: '3.1'

services:
  web:
    build: .
    volumes: 
      - ./scr:/var/www/html
    ports:
      - "80:80"
    links:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
