version: '3'
services:
  php: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootWord
      MYSQL_ROOT_USERNAME: root
      MYSQL_DATABASE: visitors
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
