CREATE DATABASE IF NOT EXISTS visitors;

USE visitors;

CREATE TABLE IF NOT EXISTS visit_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ip_address VARCHAR(45) NOT NULL,
    visit_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
